**Author:**       Jensy Gregorio Gómez 
---------------------------------------
**Profession:**  IT Support Analyst and Automatation with Python

**Date:**         24 April 2024     

**Modified** 

**Location:**     Vila Izabel, Curitiba/PR  


---

**Contacto:**

- **Email:** [contact@jensygomez.us](mailto:contact@jensygomez.us)
- **YouTube:** [Tu Canal de YouTube](https://www.youtube.com/@systechcwb826)
- **LinkedIn:** [Tu Perfil de LinkedIn](https://www.linkedin.com/in/jensygomez/)

¡Claro! Añadamos la creación de la tabla y la inserción de datos en los pasos. Aquí está la versión actualizada:

**Título:** Gestión de datos de clientes en una base de datos de ventas

**Escenario:**
Eres un analista de datos para una empresa de ventas que utiliza una base de datos para gestionar la información de los clientes. La empresa ha estado experimentando dificultades para encontrar y organizar la información de los clientes de manera eficiente. Tu jefe te ha asignado la tarea de mejorar la gestión de datos de clientes utilizando consultas SQL para ordenar y filtrar la información de la base de datos.

**Paso a paso:**

1. **Configuración inicial:**
   - Crea la base de datos "Chinook" y úsala en tu terminal MySQL.
   - Crea la tabla "Customer" con las columnas necesarias para almacenar la información del cliente:
     ```sql
     CREATE TABLE Customer (
         CustomerId INT NOT NULL,
         FirstName VARCHAR(40) NOT NULL,
         LastName VARCHAR(20) NOT NULL,
         Company VARCHAR(80),
         Address VARCHAR(70),
         City VARCHAR(40),
         State VARCHAR(40),
         Country VARCHAR(40),
         PostalCode VARCHAR(10),
         Phone VARCHAR(24),
         Fax VARCHAR(24),
         Email VARCHAR(60) NOT NULL,
         SupportRepId INT,
         CONSTRAINT PK_Customer PRIMARY KEY (CustomerId)
     );
     ```
   - Inserta los registros de datos de clientes en la tabla recién creada:
     ```sql
     INSERT INTO Customer (CustomerId, FirstName, LastName, Company, Address, City, State, Country, PostalCode, Phone, Fax, Email, SupportRepId) VALUES 
     (1, 'Luís', 'Gonçalves', 'Embraer - Empresa Brasileira de Aeronáutica S.A.', 'Av. Brigadeiro Faria Lima, 2170', 'São José dos Campos', 'SP', 'Brazil', '12227-000', '+55 (12) 3923-5555', '+55 (12) 3923-5566', 'luisg@embraer.com.br', 3),
     (2, 'Eduardo', 'Martins', 'Woodstock Discos', 'Rua Dr. Falcão Filho, 155', 'São Paulo', 'SP', 'Brazil', '01007-010', '+55 (11) 3033-5446', '+55 (11) 3033-4564', 'eduardo@woodstock.com.br', 4),
     (3, 'Alexandre', 'Rocha', 'Banco do Brasil S.A.', 'Av. Paulista, 2022', 'São Paulo', 'SP', 'Brazil', '01310-200', '+55 (11) 3055-3278', '+55 (11) 3055-8131', 'alero@uol.com.br', 5),
     (4, 'Roberto', 'Almeida', 'Riotur', 'Praça Pio X, 119', 'Rio de Janeiro', 'RJ', 'Brazil', '20040-020', '+55 (21) 2271-7000', '+55 (21) 2271-7070', 'roberto.almeida@riotur.gov.br', 3),
     (5, 'Mark', 'Philips', 'Telus', '8210 111 ST NW', 'Edmonton', 'AB', 'Canada', 'T6G 2C7', '+1 (780) 434-4554', '+1 (780) 434-5565', 'mphilips12@shaw.ca', 5),
     (6, 'Jennifer', 'Peterson', 'Rogers Canada', '700 W Pender Street', 'Vancouver', 'BC', 'Canada', 'V6C 1G8', '+1 (604) 688-2255', '+1 (604) 688-8756', 'jenniferp@rogers.ca', 3);
     ```

2. **Visualización de datos en la tabla de clientes:**
   - Escribe una consulta SQL para mostrar todos los datos existentes en la tabla de clientes.
   - Ejecuta la consulta y observa los datos mostrados en la pantalla.

3. **Ordenar el conjunto de resultados de datos:**
   - Escribe una consulta SQL para ordenar el conjunto de resultados en orden ascendente según el nombre.
   - Agrega la cláusula `ORDER BY` para ordenar los resultados por el nombre del cliente.
   - Ejecuta la consulta y observa cómo se ordenan los datos por el nombre del cliente.

4. **Filtrar el conjunto de resultados de datos:**
   - Escribe una consulta SQL para filtrar el conjunto de resultados basado en una condición donde el país sea "Canada".
   - Utiliza la cláusula `WHERE` para aplicar el filtro por país.
   - Ejecuta la consulta y observa cómo se muestran solo los clientes de Canadá.

5. **Visualización mejorada de datos:**
   - Mejora la consulta anterior para mostrar solo el nombre y el país de los clientes de Canadá.
   - Modifica la consulta para seleccionar solo las columnas de "FirstName", "LastName" y "Country".
   - Ejecuta la consulta y observa cómo se muestran solo los nombres y países de los clientes de Canadá.

6. **Finalización:**
   - Repasa los pasos realizados y confirma que has logrado ordenar y filtrar los datos de clientes de manera efectiva utilizando consultas SQL.
   - Prepárate para aplicar estos conocimientos en otras consultas y tareas de gestión de datos en la base de datos de ventas.

In [ ]:
import mysql.connector

# Conectar a la base de datos
conexion = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",  # No se necesita contraseña en tu caso
    database="cm_devices",  # Reemplaza "nombre_de_tu_base_de_datos" con el nombre de tu base de datos
    port="3306"  # Puerto por defecto de MySQL
)

if conexion.is_connected():
    print("Conexión establecida correctamente")
else:
    print("No se pudo establecer conexión")


# Definir la consulta SQL para crear la tabla
comandoSQL = """




"""

print("Comando SQL almacenado en la variable comandoSQL")


# Ejecutar la consulta SQL para crear la tabla

# Crear un cursor
cursor = conexion.cursor()

# Ejecutar la consulta para crear la tabla
cursor.execute(comandoSQL)

# Confirmar los cambios en la base de datos
conexion.commit()


# Cerrar la conexión a la base de datos al final del código
conexion.close()
print("Conexión cerrada")